sudo: required
services:
  - docker

before_install:
  - docker build -t brightside67/react-test -f ./front/Dockerfile.dev ./front

script:
  - docker run brightside67/react-test npm -v

after_success:
  - docker build -t brightside67/multi-client ./front
  - docker build -t brightside67/multi-nginx ./nginx
  - docker build -t brightside67/multi-server ./server
  - docker build -t brightside67/multi-worker ./worker
  #login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to dokcer hub
  - docker push brightside67/multi-client
  - docker push brightside67/multi-nginx
  - docker push brightside67/multi-server
  - docker push brightside67/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-634365024777
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
